# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=15000', '--enforce-all']
        exclude: |
            (?x)^(
                docs/source-pytorch/_static/images/general/fast_2.gif|
                docs/source-pytorch/_static/images/mnist_imgs/pt_to_pl.jpg|
                docs/source-pytorch/_static/images/lightning_module/pt_to_pl.png|
                docs/source-pytorch/_static/images/general/pl_quick_start_full_compressed.gif|
                docs/source-pytorch/_static/images/general/pl_overview_flat.jpg|
                docs/source-pytorch/_static/images/general/pl_overview.gif|
                src/lightning_app/cli/pl-app-template/ui/yarn.lock|
                src/pytorch_lightning/CHANGELOG.md|
                src/lightning_lite/CHANGELOG.md
            )$
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        name: Upgrade code

  - repo: https://github.com/myint/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=115, --wrap-descriptions=120]

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        name: Unused noqa

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
        args: [--max-line-length=120, "--ignore=E121,E123,E126,E203,E226,E24,E704,W503,W504", "--per-file-ignores=__init__.py:F401"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Format imports
        args: [--profile=black]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--line-length=100]
        name: Format code
        exclude: docs/source-app

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        args: [--line-length=120]
        additional_dependencies: [black==23.1.0]
        exclude: docs/source-app

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          #- mdformat-black
          - mdformat_frontmatter
        exclude: |
            (?x)^(
                src/pytorch_lightning/CHANGELOG.md|
                src/lightning_app/CHANGELOG.md|
                src/lightning_lite/CHANGELOG.md
            )$
